blank_issues_enabled: false
contact_links:
  - name: 📚 Ver PDF actualizado
    url: https://github.com/AngelFranco719/Tesis-Sistema-de-Recomendaci-n-Musical-basado-en-la-B-squeda-de-Vecinos-Aproximadamente-M-s-Cercanos/blob/main/Tesis.pdf
    about: Puedes visualizar el documento PDF haciendo click aquí.
